### ISSUE TITLE
IOS ERROR

### ISSUE THREAD

**Issue by hanwenbo** [react-native-vietnam/react-native-network-state#10]
Error when sending event: networkChanged with body: {
    isConnected = 0;
    isFast = 0;
    type = "No Connection";
}. Bridge is not set. This is probably because you've explicitly synthesized the bridge in RNNetworkState, even though it's inherited from RCTEventEmitter.
(
    "4   libc++abi.dylib                     0x000000010ecc365e _ZSt11__terminatePFvvE + 8",
    "5   libc++abi.dylib                     0x000000010ecc3307 __cxa_rethrow + 99",
    "6   libobjc.A.dylib                     0x000000010a93d8de objc_exception_rethrow + 40",
    "7   CoreFoundation                      0x00000001095aeea3 CFRunLoopRunSpecific + 771",
    "8   GraphicsServices                    0x000000010fff91dd GSEventRunModal + 62"
)

**Comment by anhtuank7c** [comment]
@hanwenbo Thank for the report. I will take a look this weekend.

**Comment by hanwenbo** [comment]
@anhtuank7c You're welcome. Thank you. It's very good.
